server:
  port: 8084

redis:
  host: 192.168.19.192
  port: 32580

spring:
#  redis:
#    host: 192.168.19.192
#    port: 32580
#datasource 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aicm@2020
    url: jdbc:mysql://192.168.19.192:32570/aicm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  # 自定义的配置文件
  mapper-locations:
    - classpath:mapping/*Mapping.xml
    - classpath:mapping/generated/*Mapping.xml
  #别名
  type-aliases-package: com.big.models
